USE rtc_digital_cards;

-- Create an admin with scripts/create_admin.php after importing the schema.
-- These sample employee records help test the results page locally before CSV import.
INSERT INTO employees (
    employee_number,
    honorific,
    suffix,
    first_name,
    last_name,
    organization,
    title,
    phone,
    email,
    street,
    city,
    region,
    postal_code,
    country,
    mecard_payload,
    qr_code_path
) VALUES
(
    'RTCZ001',
    'Ms.',
    NULL,
    'Mary',
    'Bwalya',
    'Right to Care Zambia',
    'Program Manager',
    '+260 977 123 100',
    'mary.bwalya@righttocare.org.zm',
    'Plot 12 Addis Ababa Drive',
    'Lusaka',
    'Lusaka Province',
    '10101',
    'Zambia',
    NULL,
    NULL
),
(
    'RTCZ002',
    'Mrs.',
    NULL,
    'Beatrice',
    'Malama',
    'Right to Care Zambia',
    'Admin Officer',
    '0972448338',
    'beatrice@righttocare-zambia.org',
    'Plot 12 Addis Ababa Drive',
    'Lusaka',
    'Lusaka Province',
    '10101',
    'Zambia',
    NULL,
    NULL
),
(
    'RTCZ003',
    'Mr.',
    NULL,
    'Ithamar',
    'Nyangu',
    'Right to Care Zambia',
    'Applications Developer',
    '0979511258',
    'ithamar.nyangu@righttocare-zambia.org',
    'Plot 12 Addis Ababa Drive',
    'Lusaka',
    'Lusaka Province',
    '10101',
    'Zambia',
    NULL,
    NULL
);
